### ISSUE TITLE
avconv record window in wrong place

### ISSUE THREAD

**Issue by kazzmir** [chrisbra/Replay#2]
I have avconv installed and in my path, and I set let g:record_replay=1. When I execute 'Replay' I see a rectangle with a dotted border on my screen where avconv is recording. The avconv window always appears in the upper left hand corner of my screen and is always the same size -- which is not the size of the xterm where my vim session is running.

I expected the avconv recording window to be at the same position and size as my xterm window.

As a workaround I can move my xterm to the upper left and resize it to match the avconv window.

**Comment by chrisbra** [comment]
You are right, that should work and it always did for me. Can you show me the output of 

    :exe "!xwininfo -id ". v:windowid

?

**Comment by kazzmir** [comment]
xwininfo: Window id: 0xa200024 "[No Name] + - VIM"

    Absolute upper-left X:  761
    Absolute upper-left Y:  749
    Relative upper-left X:  1
    Relative upper-left Y:  22
    Width: 1004
    Height: 664
    Depth: 24
    Visual: 0x21
    Visual Class: TrueColor
    Border width: 0
    Class: InputOutput
    Colormap: 0x20 (installed)
    Bit Gravity State: NorthWestGravity
    Window Gravity State: NorthWestGravity
    Backing Store State: NotUseful
    Save Under State: no
    Map State: IsViewable
    Override Redirect State: no
    Corners:  +761+749  -3355+749  -3355-187  +761-187
    -geometry 100x30+760+727
  
I was looking at the source and this command seems to work.

    $ avconv -f x11grab -s hd720 -show_region 1 -framerate 10 -y -s 100x100 -i :0.0+100,100 out.mkv

With -s $widthx$height and -i :0.0+$X,$Y.

I am testing this change in Replay.vim as we speak.

**Comment by kazzmir** [comment]
https://gist.github.com/kazzmir/8ba5a8d58d3ab74b1750

here is a patch that works perfectly for me

**Comment by chrisbra** [comment]
Hi Jon!

On Di, 27 Okt 2015, Jon Rafkind wrote:

> https://gist.github.com/kazzmir/8ba5a8d58d3ab74b1750
> 
> here is a patch that works perfectly for me

Thanks. I have committed that patch. Please test, I had some problems 
with applying it (I think it was missing a final newline and even after 
that some problems remained, so I fixed it manually).

Best,

## Christian

Und Bill Gates sprach: "Laßt uns doch einmal einen graphischen Virus
programmieren.

**Comment by kazzmir** [comment]
Works great for me!
